---
title: "Ejercicio Logistica: Titanic"
output: html_notebook
---

Para este ejercicio van a utilizar el dataset de Titanic de Kaggle. El mismo consiste en 2 datasets: uno de entrenamiento y otro de testeo.

El objetivo es crear un modelo usando una regresión logística para predecir que pasajeros van a sobrevivir o no. Además tienen algunas preguntas para reforzar conceptos vistos en clase.

## Lectura y analisis exploratorio

1) Carguen ambos datasets
2) Analicen su estructura
3) Revisen si existen valores faltantes y cual podria ser una estrategia para trabajar con ellos
4) Analicen cual es la cardinalidad (cantidad de valores distintos) de las variables nominales 

```{r}
train <- read.csv('train.csv')
test <- read.csv('test.csv')


```

### Graficos

Analicen las relaciones entre las variables con algunos graficos que les resulten interesantes


## Modelos iniciales

Para este caso eliminen los registros que poseen registros faltantes

1) Realicen los siguientes modelos:

a) edad= modelo solo con la edad (Age)
b) clase = modelo solo con la clase (Pclass)
c) edad+tarifa = modelo con la edad y la tarifa (Fare)
d) edad+tarifa+genero = modelo con la edad, la tarifa y el genero

2) Obtengan los valores de las estimaciones de los parametros para cada modelo

2.1) Obtengan la probabilidad de supervivencia segun los cuatro modelos de una persona que tiene 35 años, es mujer, pago una tarifa de $40 y viaja en segunda clase

2.2) Obtengan las odds segun los cuatro modelos para la misma persona

3) Ordenen los modelos por la deviance explicada

## Modelos propios

## Diagnostico

## Elección del punto de corte

## Predicción en el dataset de test


